
//Ingredient Actions

export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const LOAD_PRICE = 'LOAD_PRICE';
export const LOAD_INGREDIENT = 'LOAD_INGREDIENT';
export const LOAD_INGREDIENTS_FAILED = 'LOAD_INGREDIENTS_FAILED';

//Contact Actions

export const CHECK_VALID = 'CHECK_VALID';
export const INPUT_CHANGE = 'INPUT_CHANGE'

//Order Actions

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_INIT =  'PURCHASE_INIT';
export const ORDER_FAIL = 'ORDER_FAIL';
export const GET_ORDERS_START = 'GET_ORDER_START';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';